version: '3'
networks:
    IOT-DMS:
services:
  emqx:
    image: emqx:5.3.0
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083 
      - 8883:8883
      - 8084:8084
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    env_file:
      local_envs.env
    #environment:
    #  - name=value
    networks:
      - IOT-DMS
    restart: always

  postgres:
    container_name: postgres
    build: ./database
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - progresDB_data:/var/lib/postgresql
      - ./database/postgres.conf:/database/config/postgres.conf

    env_file:
      local_envs.env
    networks:
      - IOT-DMS
    #restart: always

  webserver:
    image: server:latest
    container_name: webserver
    build: .
    restart: always 
    ports:
    - 8080:8080
    depends_on:
      - emqx
      - postgres
    env_file:
      - local_envs.env
    networks:
      - IOT-DMS
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - postgres:postgres
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - IOT-DMS
    #restart: always
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
    networks:
      - IOT-DMS
volumes:
  grafana-storage: {}
  progresDB_data: {}
  prometheus-data:
  vol-emqx-data:
  vol-emqx-etc:
  vol-emqx-log: