version: '3'
networks:
    IOT-DMS:
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - IOT-DMS
    #restart: always

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: aaabbbccc
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - IOT-DMS
    volumes:
      - DevopsforIOT/database/postgres.conf:/var/lib/postgresql/data/pgdata
  webserver:
    image: server:latest
    container_name: webserver
    build: .
    restart: always 
    depends_on:
      - emqx
      - postgres
    env_file:
      - local_envs.env
    networks:
      - IOT-DMS
    extra_hosts:
    - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - IOT-DMS
  
  