version: '3'
networks: 
  IOT-DMS:
    external: true
services:
  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - 1884:1883
      - 8083:8083 
      - 8883:8883
      - 8084:8084
      - 18083:18083
    volumes:
    - ./emqx/conf/emqx.conf:/etc/emqx/emqx.conf
    - ./emqx/conf/acl.conf:/etc/emqx/acl.conf
    - vol-emqx-data:/opt/emqx/data
    - vol-emqx-etc:/opt/emqx/etc
    - vol-emqx-log:/opt/emqx/log
    - ./daemon.json:/etc/docker/daemon.json
    env_file:
    - local_envs.env
    networks:
    - IOT-DMS
    restart: on-failure
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
    - 9091:9091
    networks:
    - IOT-DMS
    depends_on:
    - emqx
  postgres:
    container_name: postgres
    build: ./database
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    volumes:
    - progresDB_data:/var/lib/postgresql/data
    - ./database/postgres.conf:/database/config/postgres.conf
    env_file:
    - local_envs.env
    networks:
    - IOT-DMS
    restart: on-failure
  webserver:
    image: server:latest
    container_name: webserver
    build: .
    ports:
    - 8081:8081
    depends_on:
    - emqx
    - postgres
    env_file:
    - local_envs.env
    networks:
    - IOT-DMS
    restart: on-failure
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    links:
    - postgres:postgres
    volumes:
    - grafana-storage:/var/lib/grafana
    depends_on:
    - postgres
    - emqx
    networks:
    - IOT-DMS
    #restart: always
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
    - 9093:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
    volumes:
    - prometheus-data:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - IOT-DMS
    depends_on:
    - cadvisor
    - postgres
    - webserver
    - emqx
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports: 
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
    - IOT-DMS
    depends_on:
    - postgres
    - webserver
  #alertmanager:
   # image: prom/alertmanager
    #container_name: alertmanger
   # ports:
    #- 9093:9093
    #volumes:
    #- /prometheus/alertmanager.yml:/etc/alertmanager/alermanage.yml 
    #networks: 
   # - IOT-DMS
  mytb: 
   # restart: always
    image: thingsboard/tb-postgres
    container_name: mytb
    ports:
    - 9090:9090
    - 1885:1883
    - 7070:7070
    - 5683-5688:5683-5688/udp
    environment:
     TB_QUEUE_TYPE: in-memory
    volumes:
    - mytb-data:/data
    - mytb-logs:/var/log/thingsboard
    networks:
    - IOT-DMS
    depends_on:
    - postgres
    links:
    - postgres
volumes:
  grafana-storage: {}
  progresDB_data: {}
  prometheus-data:
  vol-emqx-data:
  vol-emqx-etc:
  vol-emqx-log:
  tb-data-log: 
  tb-data-data:
  mytb-data:
  mytb-logs: