version: '3'
networks: 
  IOT-DMS:
    external: true
services:
  jenkins:
      build: ./jenkins
      container_name: jenkins
      ports:
      - 8082:8080
      - 50000:50000
      volumes:
      - devops_for_iot_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
     # env_file:
      #- local_envs.env
      networks:
      - IOT-DMS
volumes:
  devops_for_iot_jenkins_home:  
    external: true

