version: '3'
networks:
    IOT-DMS:
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - 1883:1883
      #- 8083:8083 
      #- 8883:8883
      #- 8084:8084
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    #environment:
    #  - name=value
    networks:
      - IOT-DMS
    restart: always

  postgres:
    image: postgres:alpine3.17
    container_name: postgres
    ports: 
      - '5432:5432'
    networks:
      - IOT-DMS
    volumes:
      - ./database/postgres.conf:/database/config/postgres.conf
      #- progresDB:/var/lib/porgresql/data
    env_file:
      - local_envs.env

    #restart: always

  webserver:
    image: server:latest
    container_name: webserver
    build: .
    restart: always 
    depends_on:
      - emqx
      - postgres
    env_file:
      - local_envs.env
    networks:
      - IOT-DMS
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - IOT-DMS
    restart: always