version: '3'
networks:
  IOT-DMS:
    external: true
services:
  webapp:
    container_name: webapp
    image: decalnguyen/webapp
    ports:
    - 8089:80
    env_file:
    - local_envs.env
    networks:
    - IOT-DMS
    volumes: 
    - devops_for_iot_src:/usr/src/app
    - devops_for_iot_node_modules:/usr/src/app/node_modules
    restart: always
volumes: 
  devops_for_iot_src: 
    external: true
  devops_for_iot_node_modules: 
    external: true
