version: '3'
networks: 
  IOT-DMS:
services:
  jenkins:
      image: jenkins/jenkins
      container_name: jenkins
      ports:
      - 8082:8080
      - 50000:50000
      volumes:
      - devops_for_iot_jenkins_home:/var/jenkins_home
      networks:
      - IOT-DMS
volumes:
  devops_for_iot_jenkins_home:  
    external: true

