version: '3'
networks: 
  IOT-DMS:
services:
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
    - 9091:9091
    networks:
    - IOT-DMS
    depends_on:
    - emqx
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    links:
    - postgres:postgres
    volumes:
    - grafana-storage:/var/lib/grafana
    depends_on:
    - postgres
    - emqx
    networks:
    - IOT-DMS
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
    - 9093:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
    volumes:
    - prometheus-data:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - IOT-DMS
    depends_on:
    - cadvisor
    - postgres
    - webserver
    - emqx
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports: 
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
    - IOT-DMS
    depends_on:
    - postgres
    - webserver
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
    - 8082:8080
    - 50000:50000
    volumes:
    - jenkins_home:/var/jenkins_home
    networks:
    - IOT-DMS
volumes:
  grafana-storage: {}
  prometheus-data:
  jenkins_home: {}
  tb-data-log: 
  tb-data-data:
