version: '3'
networks:
    IOT-DMS:
      external: true
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      #- 9001:9001
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - IOT-DMS
   # restart: always

  postgres:
    image: postgres:alpine3.17
    container_name: postgres
    ports:
      - 8812:8812
      - 9000:9000
    volumes:
      - ./database/postgres.conf:/database/config/postgres.conf
    environment:
      - QDB_PG_READONLY_USER_ENABLE=true
      - POSTGRES_PASSWORD=Toan02102004
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - IOT-DMS
    restart: always

  webserver:
    image: server:latest
    container_name: webserver
    build: .
    restart: always 
    depends_on:
      - mosquitto
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=IOT-DMS
      - DB_USER=nhattoan
      - POSTGRES_PASSWORD=password
    networks:
      - IOT-DMS
   # restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - IOT-DMS
    restart: always