version: '3.0'
networks:
  edgeside:
    name: edgeside
    external: true

services:
  mytbedge:
    container_name: mytbedge
    image: "thingsboard/tb-edge:3.6.1EDGE"
    ports:
      - "18080:8080"
      - "11883:1883"
      - "15683-15688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb_edge
      CLOUD_ROUTING_KEY: f472825a-57ba-f2d4-f7c5-df7a58ab3819
      CLOUD_ROUTING_SECRET: 57v1nfkcwck4npi1bijw
      CLOUD_RPC_HOST: host.docker.internal
      CLOUD_RPC_PORT: 7070
      CLOUD_RPC_SSL_ENABLED: 'false'
    volumes:
      - ~/.mytb-edge-data:/data
      - ~/.mytb-edge-logs:/var/log/tb-edge
    networks:
     - edgeside
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: postgres1
    restart: always
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: tb_edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/.mytb-edge-data/db:/var/lib/postgresql/data
    networks:
     - edgeside

