version: '3'
networks:
  Edgeside:
services:
  nanomq:
    image: emqx/nanomq:latest
    container_name: nanomq
    ports:
    - 11884:1883
    - 18084:8083
    - 18884:8883
    env_file:
    - edge-envs.env
    volumes:
    - ~/nanomq.conf:/etc
    networks:
    - Edgeside
    restart: always