version: '3'
networks:
  Edgeside:
services:
  mytbedge:
    container_name: mytbedge
    image: thingsboard/tb-edge:3.6.2EDGE
    ports:
    - 8080:8080
    - 1885:1883
    - 5683-5688:5683-5688/udp
    env_file:
    - edge-envs.env
    volumes:
    - tb-edge-data:/data
    - tb-edge-logs:/var/log/tb-edge
    restart: always
  nanomq:
    image: emqx/nanomq:latest
    container_name: nanomq
    ports:
    - 1884:1883
    - 8084:8083
    - 8884:8883
    env_file:
    - edge-envs.env
    volumes:
    - ./nanomq.conf:/etc
    networks:
    - Edgeside
    restart: always
  edge-postgres:
    image: postgres:15
    container_name: edge-postgres
    ports:
    - 5432:5432
    env_file:
    - edge-envs.env
    volumes:
    - tb-edge-postgres-data:/var/lib/postgresql/data
    restart: always
volumes:  
  tb-edge-data:
    name: tb-edge-data
  tb-edge-logs:
    name: tb-edge-logs
  tb-edge-postgres-data:
    name: tb-edge-postgres-data

