global: 
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'
rule_files:
  - 'prometheus.rules.yml'
scrape_configs:
  -job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor: 9191
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 9090

    