global:
  scrape_interval: 1m

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'emqx'
    scrape_interval: 5s
    static_configs:
      - targets: ['emqx:1883']
  - job_name: 'webserver'
    scrape_interval: 5s
    static_configs:
      - targets: ['webserver:8081']

    