version: '3'
networks:
  IOT-DMS:
    external: true
services:
  postgres:
    container_name: postgres
    build: ~/Devops_for_iot/database/
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    volumes:
    - progresDB_data:/var/lib/postgresql/data
    - ~/Devops_for_iot/database/postgres.conf:/database/config/postgres.conf
    env_file:
    - ~/Devops_for_iot/local_envs.env
    networks:
    - IOT-DMS
    restart: on-failure
volumes:
  progresDB_data: {}